config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'

  resources :cocktails, only: [:index, :new, :show, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  # cocktail doesn't have the ID of ingredients, so it has to go through doses
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates_uniqueness_of :ingredient_id, scope: :cocktail_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end


  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end


  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = @dose.cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id]).destroy
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.pexels.com/photos/4784/alcohol-bar-party-cocktail.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');">
  <div class="banner-content">
    <h1 class="banner-title">Calvin's Cocktails</h1>
    <p>Check out our latest concoctions</p>
  </div>
</div>

app/views/cocktails/_cocktails.html.erb
<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <%= link_to cocktail_path(cocktail) do  %>
        <div class="col col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cocktail.photo? ? (cl_image_path cocktail.photo) : (image_path 'defaultcocktail.jpeg') %>');">
            <div class="card-description">
              <h2 class="cocktail-name"><%= cocktail.name %></h2>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<!-- cocktail.photo? ? cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill : image_path 'defaultcocktail.jpeg' -->

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, label: 'Create!', class:"btn btn-success"%>
  </div>
<% end %>

app/views/cocktails/index.html.erb
  <%= render 'banner' %>
<div class="background-cover">
  <%= render 'cocktails' %>
  <%= link_to 'New Cocktail', new_cocktail_path, class:"btn btn-light btn-block "  %>
</div>

app/views/cocktails/new.html.erb
<h1>Create a new cocktail</h1>
<%= render 'form' %>

app/views/cocktails/show.html.erb
<div class="show-wrapper">
  <%= cl_image_tag @cocktail.photo, crop: :fill %>
</div>
<h1><%= @cocktail.name %></h1>
<%= link_to 'New Dose', new_cocktail_dose_path(@cocktail)  %>
<p>new dose link</p>

app/views/doses/new.html.erb
<p>add a form that creates a new dose</p>
<p>dose form has ingredients drop down and "dose description"</p>
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :ingredient_id, collections: @ingredients %>
  <%= f.input :description %>
<% end %>

app/views/doses/show.html.erb
<!-- create a form -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>